<?php
return [
		'Alexandria'        => __( 'Alexandria', 'daleel-arabic-states-for-woocommerce' ),
		'Aswan'             => __( 'Aswan', 'daleel-arabic-states-for-woocommerce' ),
		'Asyut'             => __( 'Asyut', 'daleel-arabic-states-for-woocommerce' ),
		'Red Sea'           => __( 'Red Sea', 'daleel-arabic-states-for-woocommerce' ),
		'Beheira'           => __( 'Beheira', 'daleel-arabic-states-for-woocommerce' ),
		'Beni Suef'         => __( 'Beni Suef', 'daleel-arabic-states-for-woocommerce' ),
		'Cairo'             => __( 'Cairo', 'daleel-arabic-states-for-woocommerce' ),
		'Dakahlia'          => __( 'Dakahlia', 'daleel-arabic-states-for-woocommerce' ),
		'Damietta'          => __( 'Damietta', 'daleel-arabic-states-for-woocommerce' ),
		'Faiyum'            => __( 'Faiyum', 'daleel-arabic-states-for-woocommerce' ),
		'Gharbia'           => __( 'Gharbia', 'daleel-arabic-states-for-woocommerce' ),
		'Giza'              => __( 'Giza', 'daleel-arabic-states-for-woocommerce' ),
		'Ismailia'          => __( 'Ismailia', 'daleel-arabic-states-for-woocommerce' ),
		'South Sinai'       => __( 'South Sinai', 'daleel-arabic-states-for-woocommerce' ),
		'Qalyubia'          => __( 'Qalyubia', 'daleel-arabic-states-for-woocommerce' ),
		'Kafr El Sheikh'    => __( 'Kafr El Sheikh', 'daleel-arabic-states-for-woocommerce' ),
		'Qena'              => __( 'Qena', 'daleel-arabic-states-for-woocommerce' ),
		'Luxor'             => __( 'Luxor', 'daleel-arabic-states-for-woocommerce' ),
		'Minya'             => __( 'Minya', 'daleel-arabic-states-for-woocommerce' ),
		'Monufia'           => __( 'Monufia', 'daleel-arabic-states-for-woocommerce' ),
		'Matrouh'           => __( 'Matrouh', 'daleel-arabic-states-for-woocommerce' ),
		'Port Said'         => __( 'Port Said', 'daleel-arabic-states-for-woocommerce' ),
		'Sohag'             => __( 'Sohag', 'daleel-arabic-states-for-woocommerce' ),
		'Al Sharqia'        => __( 'Al Sharqia', 'daleel-arabic-states-for-woocommerce' ),
		'North Sinai'       => __( 'North Sinai', 'daleel-arabic-states-for-woocommerce' ),
		'Suez'              => __( 'Suez', 'daleel-arabic-states-for-woocommerce' ),
		'New Valley'        => __( 'New Valley', 'daleel-arabic-states-for-woocommerce' ),
];
