<?php
return [
    'Ahmadi'           => __( 'Ahmadi', 'daleel-arabic-states-for-woocommerce' ),
    'Bayan'            => __( 'Bayan', 'daleel-arabic-states-for-woocommerce' ),
    'Dasma'            => __( 'Dasma', 'daleel-arabic-states-for-woocommerce' ),
    'Fahaheel'         => __( 'Fahaheel', 'daleel-arabic-states-for-woocommerce' ),
    'Farwaniya'        => __( 'Farwaniya', 'daleel-arabic-states-for-woocommerce' ),
    'Fintas'           => __( 'Fintas', 'daleel-arabic-states-for-woocommerce' ),
    'Jabriya'          => __( 'Jabriya', 'daleel-arabic-states-for-woocommerce' ),
    'Jahra'            => __( 'Jahra', 'daleel-arabic-states-for-woocommerce' ),
    'Kuwait City'      => __( 'Kuwait City', 'daleel-arabic-states-for-woocommerce' ),
    'Mahboula'         => __( 'Mahboula', 'daleel-arabic-states-for-woocommerce' ),
    'Mishref'          => __( 'Mishref', 'daleel-arabic-states-for-woocommerce' ),
    'Omariya'          => __( 'Omariya', 'daleel-arabic-states-for-woocommerce' ),
    'Rabiya'           => __( 'Rabiya', 'daleel-arabic-states-for-woocommerce' ),
    'Rumaithiya'       => __( 'Rumaithiya', 'daleel-arabic-states-for-woocommerce' ),
    'Sabah Al-Salem'   => __( 'Sabah Al-Salem', 'daleel-arabic-states-for-woocommerce' ),
    'Salmiya'          => __( 'Salmiya', 'daleel-arabic-states-for-woocommerce' ),
    'Salwa'            => __( 'Salwa', 'daleel-arabic-states-for-woocommerce' ),
    'Shamiya'          => __( 'Shamiya', 'daleel-arabic-states-for-woocommerce' ),
    'South Surra'      => __( 'South Surra', 'daleel-arabic-states-for-woocommerce' ),
    'Wafra'            => __( 'Wafra', 'daleel-arabic-states-for-woocommerce' ),
    'Zour'             => __( 'Zour', 'daleel-arabic-states-for-woocommerce' ),
];
