<?php
return [
    'Abha'             => __( 'Abha', 'daleel-arabic-states-for-woocommerce' ),
    'Al Bahah'         => __( 'Al Bahah', 'daleel-arabic-states-for-woocommerce' ),
    'Al Dammam'        => __( 'Al Dammam', 'daleel-arabic-states-for-woocommerce' ),
    'Al Jubail'        => __( 'Al Jubail', 'daleel-arabic-states-for-woocommerce' ),
    'Al Khobar'        => __( 'Al Khobar', 'daleel-arabic-states-for-woocommerce' ),
    'Al Majmaah'       => __( 'Al Majmaah', 'daleel-arabic-states-for-woocommerce' ),
    'Al Qatif'         => __( 'Al Qatif', 'daleel-arabic-states-for-woocommerce' ),
    'Arar'             => __( 'Arar', 'daleel-arabic-states-for-woocommerce' ),
    'Buraidah'         => __( 'Buraidah', 'daleel-arabic-states-for-woocommerce' ),
    'Dhahran'          => __( 'Dhahran', 'daleel-arabic-states-for-woocommerce' ),
    'Hafar Al-Batin'   => __( 'Hafar Al-Batin', 'daleel-arabic-states-for-woocommerce' ),
    'Hail'             => __( 'Hail', 'daleel-arabic-states-for-woocommerce' ),
    'Jazan'            => __( 'Jazan', 'daleel-arabic-states-for-woocommerce' ),
    'Jeddah'           => __( 'Jeddah', 'daleel-arabic-states-for-woocommerce' ),
    'Khamis Mushait'   => __( 'Khamis Mushait', 'daleel-arabic-states-for-woocommerce' ),
    'Madinah'          => __( 'Madinah', 'daleel-arabic-states-for-woocommerce' ),
    'Makkah'           => __( 'Makkah', 'daleel-arabic-states-for-woocommerce' ),
    'Najran'           => __( 'Najran', 'daleel-arabic-states-for-woocommerce' ),
    'Riyadh'           => __( 'Riyadh', 'daleel-arabic-states-for-woocommerce' ),
    'Sakaka'           => __( 'Sakaka', 'daleel-arabic-states-for-woocommerce' ),
    'Sulaymaniyah'     => __( 'Sulaymaniyah', 'daleel-arabic-states-for-woocommerce' ),
    'Tabuk'            => __( 'Tabuk', 'daleel-arabic-states-for-woocommerce' ),
    'Taif'             => __( 'Taif', 'daleel-arabic-states-for-woocommerce' ),
    'Unaizah'          => __( 'Unaizah', 'daleel-arabic-states-for-woocommerce' ),
    'Yanbu'            => __( 'Yanbu', 'daleel-arabic-states-for-woocommerce' ),
];

