<?php
return [
    'Atbara'           => __( 'Atbara', 'daleel-arabic-states-for-woocommerce' ),
    'Babnousa'         => __( 'Babnousa', 'daleel-arabic-states-for-woocommerce' ),
    'Bahri'            => __( 'Bahri', 'daleel-arabic-states-for-woocommerce' ),
    'Damazin'          => __( 'Damazin', 'daleel-arabic-states-for-woocommerce' ),
    'Dongola'          => __( 'Dongola', 'daleel-arabic-states-for-woocommerce' ),
    'Duiem'            => __( 'Duiem', 'daleel-arabic-states-for-woocommerce' ),
    'El Fasher'        => __( 'El Fasher', 'daleel-arabic-states-for-woocommerce' ),
    'El Geneina'       => __( 'El Geneina', 'daleel-arabic-states-for-woocommerce' ),
    'El Obeid'         => __( 'El Obeid', 'daleel-arabic-states-for-woocommerce' ),
    'Gedaref'          => __( 'Gedaref', 'daleel-arabic-states-for-woocommerce' ),
    'Halfa Al Jadida'  => __( 'Halfa Al Jadida', 'daleel-arabic-states-for-woocommerce' ),
    'Khartoum'         => __( 'Khartoum', 'daleel-arabic-states-for-woocommerce' ),
    'Kosti'            => __( 'Kosti', 'daleel-arabic-states-for-woocommerce' ),
    'Kassala'          => __( 'Kassala', 'daleel-arabic-states-for-woocommerce' ),
    'Nyala'            => __( 'Nyala', 'daleel-arabic-states-for-woocommerce' ),
    'Port Sudan'       => __( 'Port Sudan', 'daleel-arabic-states-for-woocommerce' ),
    'Rabak'            => __( 'Rabak', 'daleel-arabic-states-for-woocommerce' ),
    'Sennar'           => __( 'Sennar', 'daleel-arabic-states-for-woocommerce' ),
    'Shandi'           => __( 'Shandi', 'daleel-arabic-states-for-woocommerce' ),
    'Sawakin'          => __( 'Sawakin', 'daleel-arabic-states-for-woocommerce' ),
    'Tabat'            => __( 'Tabat', 'daleel-arabic-states-for-woocommerce' ),
    'Wad Madani'       => __( 'Wad Madani', 'daleel-arabic-states-for-woocommerce' ),
    'Wadi Halfa'       => __( 'Wadi Halfa', 'daleel-arabic-states-for-woocommerce' ),
];
