<?php
return [
    'Ariana'           => __( 'Ariana', 'daleel-arabic-states-for-woocommerce' ),
    'Bajet'            => __( 'Bajet', 'daleel-arabic-states-for-woocommerce' ),
    'Benghazi'         => __( 'Benghazi', 'daleel-arabic-states-for-woocommerce' ),
    'Bizerte'          => __( 'Bizerte', 'daleel-arabic-states-for-woocommerce' ),
    'Capes'            => __( 'Capes', 'daleel-arabic-states-for-woocommerce' ),
    'Gafsa'            => __( 'Gafsa', 'daleel-arabic-states-for-woocommerce' ),
    'Gendouba'         => __( 'Gendouba', 'daleel-arabic-states-for-woocommerce' ),
    'Kasserine'        => __( 'Kasserine', 'daleel-arabic-states-for-woocommerce' ),
    'Kef'              => __( 'Kef', 'daleel-arabic-states-for-woocommerce' ),
    'Mahdia'           => __( 'Mahdia', 'daleel-arabic-states-for-woocommerce' ),
    'Manouba'          => __( 'Manouba', 'daleel-arabic-states-for-woocommerce' ),
    'Medenine'         => __( 'Medenine', 'daleel-arabic-states-for-woocommerce' ),
    'Monastir'         => __( 'Monastir', 'daleel-arabic-states-for-woocommerce' ),
    'Nabeul'           => __( 'Nabeul', 'daleel-arabic-states-for-woocommerce' ),
    'Sfax'             => __( 'Sfax', 'daleel-arabic-states-for-woocommerce' ),
    'Sidi Bouzid'      => __( 'Sidi Bouzid', 'daleel-arabic-states-for-woocommerce' ),
    'Siliana'          => __( 'Siliana', 'daleel-arabic-states-for-woocommerce' ),
    'Tataouine'        => __( 'Tataouine', 'daleel-arabic-states-for-woocommerce' ),
    'Tozeur'           => __( 'Tozeur', 'daleel-arabic-states-for-woocommerce' ),
    'Tunis'            => __( 'Tunis', 'daleel-arabic-states-for-woocommerce' ),
    'Zaghouan'         => __( 'Zaghouan', 'daleel-arabic-states-for-woocommerce' ),
];
