<?php
return [
    'Abyan'            => __( 'Abyan', 'daleel-arabic-states-for-woocommerce' ),
    'Aden'             => __( 'Aden', 'daleel-arabic-states-for-woocommerce' ),
    'Amana Capital'    => __( 'Amana Capital', 'daleel-arabic-states-for-woocommerce' ),
    'Al-Bayda'         => __( 'Al-Bayda', 'daleel-arabic-states-for-woocommerce' ),
    'Al-Dhala'         => __( 'Al-Dhala', 'daleel-arabic-states-for-woocommerce' ),
    'Al-Hudaydah'      => __( 'Al-Hudaydah', 'daleel-arabic-states-for-woocommerce' ),
    'Al-Jawf'          => __( 'Al-Jawf', 'daleel-arabic-states-for-woocommerce' ),
    'Al-Mahrah'        => __( 'Al-Mahrah', 'daleel-arabic-states-for-woocommerce' ),
    'Al-Mahwit'        => __( 'Al-Mahwit', 'daleel-arabic-states-for-woocommerce' ),
    'Hadramaut'        => __( 'Hadramaut', 'daleel-arabic-states-for-woocommerce' ),
    'Hajja'            => __( 'Hajja', 'daleel-arabic-states-for-woocommerce' ),
    'Ibb'              => __( 'Ibb', 'daleel-arabic-states-for-woocommerce' ),
    'Lahj'             => __( 'Lahj', 'daleel-arabic-states-for-woocommerce' ),
    'Ma\'rib'          => __( 'Ma\'rib', 'daleel-arabic-states-for-woocommerce' ),
    'Maqab'            => __( 'Maqab', 'daleel-arabic-states-for-woocommerce' ),
    'Sana\'a'          => __( 'Sana\'a', 'daleel-arabic-states-for-woocommerce' ),
    'Saidah'           => __( 'Saidah', 'daleel-arabic-states-for-woocommerce' ),
    'Shabwa'           => __( 'Shabwa', 'daleel-arabic-states-for-woocommerce' ),
    'Sukutra'          => __( 'Sukutra', 'daleel-arabic-states-for-woocommerce' ),
    'Taiz'             => __( 'Taiz', 'daleel-arabic-states-for-woocommerce' ),
    'Thamar'           => __( 'Thamar', 'daleel-arabic-states-for-woocommerce' ),
];
